name: Container build & publish
on:
  push:
    branches:
      - main
env:
  VERSION: "0.1"
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build -t "ghcr.io/${{ github.repository_owner }}/john:${VERSION}" .
      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Publish
        run: docker push "ghcr.io/${{ github.repository_owner }}/john:${VERSION}"